name: Feature Request 
description: Request a Feature!
title: "[feature]: "
labels: ["feature", "Up for Grabs"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-is-the-feature
    attributes:
      label: What should be changed?
      description: Explain in detail what the feature is and why it is needed. 
    validations:
      required: true